version: "3.9"

services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
      elasticsearchport: 9200

  elastic-readiness:
    image: curlimages/curl
    links:
      - elastic
    command:
          - sh
          - -c
          - "curl -XGET --fail http://elastic:9200/_cluster/health --connect-timeout 1"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 10

  app:
    build: ./app
    links:
      -  elastic-readiness
    ports:
      - "5000:5000"
    environment:
      elasticsearchsvc: elastic
      elasticsearchport: 9200
    depends_on:
      elastic-readiness:
        condition: service_completed_successfully
