# Default values for python-web-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

elastic:
  enabled: true
  image:
    repository: docker.elastic.co/elasticsearch/elasticsearch
    pullPolicy: IfNotPresent
    tag: "7.11.0"
  podAnnotations: {}
  serviceAccount:
    create: true
    annotations: {}
  environment:
    discoveryType: single-node
    esJavaOpts: "-Xmx128m -Xms128m"
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  persistence:
    enabled: false
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi
    annotations: {}
  securityContext:
    enabled: false
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  service:
    annotations: {}
    type: ClusterIP
    port: 9200
  initContainer:
    image: "busybox"
    tag: "1.32"
    resources:
      requests:
        memory: 10Mi
        cpu: 10m

pythonapp:
  enabled: true
  serviceAccount:
    create: true
  service:
    type: ClusterIP
    port: 5000
  replicaCount: 1
  image:
    repository: pendelamani/pythonapp 
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
  initContainer:
    image: "curlimages/curl"
    pullPolicy: IfNotPresent
    resources:
      requests:
        memory: 10Mi
        cpu: 10m
  elasticsearchUrl: "elastic-svc:9200"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    successThreshold: 1
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  ingress:
    enabled: false
    annotations: {}
    className: ""
    pathtype: ImplementationSpecific
    hosts:
      - host: k8host
        paths:
          - path: /
    tls: []
    #  - secretName: tls
    #    hosts:
    #      - k8host.local

global:
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  elasticsearchSvc: elastic-svc
  elasticsearchPort: 9200

