apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "elastic.fullname" . }}
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "elastic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "elastic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
       {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "elastic.serviceAccountName" . }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      {{- end }}
      containers:
        - name: {{ template "elastic.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: ealsticport
              containerPort: 9200
            - name: transport
              containerPort: 9300
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          env:
            - name: discovery.type
              value: {{ .Values.environment.discoveryType }}
            - name: ES_JAVA_OPTS
              value: {{ .Values.environment.esJavaOpts }}
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:    
        - name: elasticsearch-data
        {{- if and .Values.persistence.enabled (not (empty .Values.persistence.storageClass)) }}
          persistentVolumeClaim:
            claimName: {{ template "elastic.fullname" . }}
        {{- else }}
          emptyDir: {}
        {{- end -}}


