{{- if and .Values.persistence.enabled (not (empty .Values.persistence.storageClass)) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "elastic.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
{{- with .Values.persistence.Annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  storageClassName: "{{ .Values.persistence.storageClass }}"
{{- end }}