apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.elasticsearchSvc }}
  labels:
    {{- include "elastic.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ealsticport
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.global.elasticsearchPort }}
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.gloabl.elasticsearchPort }}
    {{- end }}
  selector:
    {{- include "elastic.selectorLabels" . | nindent 4 }}